parameters:
  - name: serviceConnection
    type: string
  - name: subscriptionId
    type: string
  - name: environment
    type: string
  - name: workingDirectory
    type: string
  - name: runPlanInApply
    type: boolean
    default: false

stages:
  # Plan Stage
  - stage: Plan_${{ parameters.environment }}
    displayName: 'Plan: Subscriptions (${{ parameters.environment }})'
    jobs:
      - job: TfPlan
        displayName: 'Plan: Subscriptions ${{ parameters.environment }}'
        steps:
          - task: AzureCLI@2
            displayName: "Plan: Terraform Subscriptions"
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Set Azure context to the specified subscription
                az account set --subscription "${{ parameters.subscriptionId }}"
                
                cd ${{ parameters.workingDirectory }}
                
                # Get Azure context and set ARM variables for Azure provider authentication
                SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                TENANT_ID=$(az account show --query tenantId -o tsv)
                CLIENT_ID=$(az account show --query user.name -o tsv)
                
                # Set ARM environment variables for Terraform Azure provider
                export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
                export ARM_TENANT_ID=$TENANT_ID
                export ARM_CLIENT_ID=$CLIENT_ID
                export ARM_USE_OIDC=true
                
                # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
                unset AZURE_CONFIG_DIR
                
                echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
                echo "ARM_TENANT_ID: $ARM_TENANT_ID"
                echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
                echo "ARM_USE_OIDC: $ARM_USE_OIDC"
                
                terraform init -upgrade

                terraform plan

  # Apply Stage
  - stage: Apply_${{ parameters.environment }}
    displayName: 'Apply: Subscriptions (${{ parameters.environment }})'
    dependsOn: Plan_${{ parameters.environment }}
    jobs:
      - deployment: TfApply
        displayName: 'Apply: Subscriptions ${{ parameters.environment }}'
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: "Apply: Terraform Subscriptions"
                  inputs:
                    azureSubscription: ${{ parameters.serviceConnection }}
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Set Azure context to the specified subscription
                      az account set --subscription "${{ parameters.subscriptionId }}"
                      
                      cd ${{ parameters.workingDirectory }}
                       
                      # Get Azure context and set ARM variables for Azure provider authentication
                      SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                      TENANT_ID=$(az account show --query tenantId -o tsv)
                      CLIENT_ID=$(az account show --query user.name -o tsv)
                      
                      # Set ARM environment variables for Terraform Azure provider
                      export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
                      export ARM_TENANT_ID=$TENANT_ID
                      export ARM_CLIENT_ID=$CLIENT_ID
                      export ARM_USE_OIDC=true
                      
                      # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
                      unset AZURE_CONFIG_DIR
                      
                      echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
                      echo "ARM_TENANT_ID: $ARM_TENANT_ID"
                      echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
                      echo "ARM_USE_OIDC: $ARM_USE_OIDC"
                      
                      terraform init -upgrade
                      
                      if [ "${{ parameters.runPlanInApply }}" = "true" ]; then
                        terraform plan
                      fi

                      terraform apply -auto-approve
